services:
  ab.testing.manager:
    class: AB\ABBundle\Base\DoctrineManager
    arguments:
      - "@doctrine.odm.mongodb.default_document_manager" 
      - "ABBundle:TestSuite" 
      - "AB\ABBundle\Document\TestSuite"
