services:
  ab.testing.session:
    class: AB\ABBundle\Base\HttpSession
    arguments:
      - "@session"
  ab.testing.service:
    class: AB\ABBundle\Service\Service
    arguments:
      - "@ab.testing.manager"
      - "@ab.testing.session"
